### ISSUE TITLE
[Question] Cannot sign in with admin user.

### ISSUE THREAD

**Issue by RedGamingBlue** [nioc/web-music-player#56]
I went through all the setup and made sqlite database. When I try to sign in with user "admin" and my admin password that I set it says invalid credentials. I do not know much about using databases so I couldn't figure it out. Please let me know what information I would need to provide.

**Comment by nioc** [comment]
Hello, I wrote this 5 years ago and I'll have to install it with SQLlite for answering you.
I'll look at it next week, keep me posted if you find a solution before 😉

**Comment by nioc** [comment]
Hello @RedGamingBlue I just tested a new installation in docker container, there was some issues with permissions but it worked as expected (I typed an admin password and login with `admin` login and the typed password).

Try to delete your previous installation and make sure there is no error during setup process (all step are green):
![image](https://user-images.githubusercontent.com/5225411/153763102-76ee2a26-1caf-44b2-86b1-07091db5c7b2.png)

Also make sure there is no permission/path issue:
- `SQLite database path` is relative to the root Apache path, in my test I keep default value, so the database is located in `/var/www/html/server/data/wmp.sqlite`, the folder must be writable by Apache user (www-data)
- `/var/www/html/server/configuration/local.ini` must be writable by Apache user too

And last but not least, make sure `sqlite3` is installed and usable by your php:
```
root@554627f80101:/var/www/html/server/data# dpkg --list | grep sqlite
ii  libaprutil1-dbd-sqlite3:amd64 1.6.1-5                        amd64        Apache Portable Runtime Utility Library - SQLite3 Driver
ii  libsqlite3-0:amd64            3.34.1-3                       amd64        SQLite 3 shared library
ii  sqlite3                       3.34.1-3                       amd64        Command line interface for SQLite 3


root@554627f80101:/var/www/html/server/data# php -m | grep sqlite
pdo_sqlite
sqlite3
```

**Comment by nioc** [comment]
Stale
